// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandologicTechTestApi.Models;

#nullable disable

namespace PandologicTechTestApi.Migrations
{
    [DbContext(typeof(JobStatisticsContext))]
    [Migration("20220421184536_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PandologicTechTestApi.Models.JobStatisticsPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("ActiveJobs")
                        .HasColumnType("int");

                    b.Property<int>("CumulativeJobViews")
                        .HasColumnType("int");

                    b.Property<int>("CumulativePredictedJobView")
                        .HasColumnType("int");

                    b.Property<DateTime>("DayDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobStatisticsPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
